spring.application.name=FineApp
spring.datasource.url=jdbc:postgresql://localhost:5432/fineapp
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=aboba
spring.security.user.password=123

spring.data.redis.host=redis-19091.c55.eu-central-1-1.ec2.redns.redis-cloud.com
spring.data.redis.port=19091
spring.data.redis.username=default
spring.data.redis.password=ULMwjzLj1RVcawPUoUJZsVo3SeFPASpg
spring.data.redis.ssl.enabled=true